export default ROUTES = {
  Auth: "Auth",
  App: "App",
  Loading: "loading",
  Login: "login",
  Register: "register",
  Verify: "verify",
  Dashboard: "dashboard",
  Task: "task",
  TaskAudio: "task_audio",
  TaskVideo: "task_video",
  Search: "search",
  History: "history",
  Profile: "profile",
}
